/* eslint-disable no-template-curly-in-string */
const VBEN_SCRIPT_SNIPPETS = [
  {
    prefix: 'vb-alert',
    imports: [
      {
        names: ['alert'],
        source: '@vben/common-ui',
        type: false,
      },
    ],
    detail: 'Vben 提示框（alert）',
    description: '插入基础 alert 用法片段。',
    body: [
      "import { alert } from '@vben/common-ui';",
      '',
      'function ${1:showAlert}() {',
      '  alert({',
      "    content: '${2:这是一条提示消息}',",
      '  });',
      '}',
    ].join('\n'),
  },
  {
    prefix: 'vb-confirm',
    imports: [
      {
        names: ['alert', 'confirm'],
        source: '@vben/common-ui',
        type: false,
      },
    ],
    detail: 'Vben 提示框（confirm）',
    description: '插入基础 confirm 用法片段。',
    body: [
      "import { alert, confirm } from '@vben/common-ui';",
      '',
      'async function ${1:showConfirm}() {',
      '  try {',
      '    await confirm({',
      "      content: '${2:确认继续吗？}',",
      '      showCancel: true,',
      '    });',
      "    alert('${3:已确认}');",
      '  } catch {',
      "    alert('${4:已取消}');",
      '  }',
      '}',
    ].join('\n'),
  },
  {
    prefix: 'vb-prompt',
    imports: [
      {
        names: ['alert', 'prompt'],
        source: '@vben/common-ui',
        type: false,
      },
    ],
    detail: 'Vben 提示框（prompt）',
    description: '插入基础 prompt 用法片段。',
    body: [
      "import { alert, prompt } from '@vben/common-ui';",
      '',
      'async function ${1:showPrompt}() {',
      '  const value = await prompt({',
      "    content: '${2:请输入一些内容}',",
      "    defaultValue: '${3:}',",
      '  });',
      '  if (value) {',
      "    alert('输入内容: ' + value);",
      '  }',
      '}',
    ].join('\n'),
  },
  {
    prefix: 'vb-modal',
    imports: [
      {
        names: ['useVbenModal'],
        source: '@vben/common-ui',
        type: false,
      },
    ],
    detail: 'Vben 弹窗（useVbenModal）',
    description: '插入 useVbenModal 初始化片段。',
    body: [
      "import { useVbenModal } from '@vben/common-ui';",
      '',
      'const [${1:Modal}, ${2:modalApi}] = useVbenModal({',
      "  title: '${3:基础示例}',",
      '});',
    ].join('\n'),
  },
  {
    prefix: 'vb-drawer',
    imports: [
      {
        names: ['useVbenDrawer'],
        source: '@vben/common-ui',
        type: false,
      },
    ],
    detail: 'Vben 抽屉（useVbenDrawer）',
    description: '插入 useVbenDrawer 初始化片段。',
    body: [
      "import { useVbenDrawer } from '@vben/common-ui';",
      '',
      'const [${1:Drawer}, ${2:drawerApi}] = useVbenDrawer({',
      "  title: '${3:基础示例}',",
      '});',
    ].join('\n'),
  },
  {
    prefix: 'vb-form',
    imports: [
      {
        names: ['useVbenForm'],
        source: '#/adapter/form',
        type: false,
      },
    ],
    detail: 'Vben 表单（useVbenForm）',
    description: '插入 useVbenForm 基础 schema 片段。',
    body: [
      "import { useVbenForm } from '#/adapter/form';",
      '',
      'const [${1:Form}, ${2:formApi}] = useVbenForm({',
      '  handleSubmit: ${3:onSubmit},',
      '  schema: [',
      '    {',
      "      component: 'Input',",
      "      fieldName: '${4:关键词}',",
      "      label: '${5:关键词}',",
      '      componentProps: {',
      "        placeholder: '${6:请输入}',",
      '      },',
      '    },',
      '  ],',
      '});',
      '',
      'function ${3:onSubmit}(values) {',
      '  console.log(values);',
      '}',
    ].join('\n'),
  },
  {
    prefix: 'vb-vxe-table',
    imports: [
      {
        names: ['VxeGridProps'],
        source: '#/adapter/vxe-table',
        type: true,
      },
      {
        names: ['useVbenVxeGrid'],
        source: '#/adapter/vxe-table',
        type: false,
      },
    ],
    detail: 'Vben Vxe 表格（useVbenVxeGrid）',
    description: '插入 useVbenVxeGrid 基础片段。',
    body: [
      "import type { VxeGridProps } from '#/adapter/vxe-table';",
      "import { useVbenVxeGrid } from '#/adapter/vxe-table';",
      '',
      'interface ${1:RowType} {',
      '  id: number;',
      '  name: string;',
      '}',
      '',
      'const ${2:gridOptions}: VxeGridProps<${1:RowType}> = {',
      '  columns: [',
      "    { field: 'name', title: '名称' },",
      '  ],',
      '  data: [],',
      '  pagerConfig: {',
      '    enabled: false,',
      '  },',
      '};',
      '',
      'const [${3:Grid}, ${4:gridApi}] = useVbenVxeGrid({',
      '  gridOptions: ${2:gridOptions},',
      '});',
    ].join('\n'),
  },
];

const VBEN_PAGE_TEMPLATE_SNIPPETS = [
  {
    prefix: 'vb-page',
    detail: 'Vben 页面（完整 SFC 模板）',
    description: '插入包含 script 与 template 的完整 Page SFC 模板。',
    body: [
      '<script lang="ts" setup>',
      "import { Page } from '@vben/common-ui';",
      '</script>',
      '',
      '<template>',
      '  <Page title="${1:页面标题}" description="${2:页面描述}" auto-content-height />',
      '</template>',
      '$0',
    ].join('\n'),
  },
];

const DOCS_URL = {
  page: 'https://doc.vben.pro/components/layout-ui/page.html',
  vbenAlert: 'https://doc.vben.pro/components/common-ui/vben-alert.html',
  vbenDrawer: 'https://doc.vben.pro/components/common-ui/vben-drawer.html',
  vbenForm: 'https://doc.vben.pro/components/common-ui/vben-form.html',
  vbenModal: 'https://doc.vben.pro/components/common-ui/vben-modal.html',
  vbenVxeTable: 'https://doc.vben.pro/components/common-ui/vben-vxe-table.html',
};

const SNIPPET_DOCS_URL_MAP = {
  'vb-alert': DOCS_URL.vbenAlert,
  'vb-confirm': DOCS_URL.vbenAlert,
  'vb-prompt': DOCS_URL.vbenAlert,
  'vb-modal': DOCS_URL.vbenModal,
  'vb-drawer': DOCS_URL.vbenDrawer,
  'vb-form': DOCS_URL.vbenForm,
  'vb-vxe-table': DOCS_URL.vbenVxeTable,
  'vb-page': DOCS_URL.page,
};

const FUNCTION_DOCS_URL_MAP = {
  alert: DOCS_URL.vbenAlert,
  confirm: DOCS_URL.vbenAlert,
  prompt: DOCS_URL.vbenAlert,
  VxeGridEvents: DOCS_URL.vbenVxeTable,
  VxeGridProps: DOCS_URL.vbenVxeTable,
  useVbenDrawer: DOCS_URL.vbenDrawer,
  useVbenForm: DOCS_URL.vbenForm,
  useVbenModal: DOCS_URL.vbenModal,
  useVbenVxeGrid: DOCS_URL.vbenVxeTable,
};

const API_DOCS_URL_MAP = {
  drawerApi: DOCS_URL.vbenDrawer,
  formApi: DOCS_URL.vbenForm,
  gridApi: DOCS_URL.vbenVxeTable,
  modalApi: DOCS_URL.vbenModal,
};

const COMPONENT_OPTION_META = {
  useVbenDrawer: {
    appendToMain: '是否挂载到主内容区域',
    cancelText: '取消按钮文本',
    class: '抽屉根节点类名',
    closable: '是否显示关闭按钮',
    closeIconPlacement: '关闭按钮位置（左/右：left/right）',
    closeOnClickModal: '点击遮罩时是否关闭',
    closeOnPressEscape: '按 ESC 时是否关闭',
    confirmLoading: '确认按钮加载状态',
    confirmText: '确认按钮文本',
    contentClass: '内容区域类名',
    description: '抽屉描述文案',
    destroyOnClose: '关闭后是否销毁内容',
    footer: '是否显示底部操作区',
    footerClass: '底部区域类名',
    header: '是否显示头部',
    headerClass: '头部区域类名',
    isOpen: '是否处于打开状态',
    loading: '是否显示整体加载状态',
    modal: '是否显示遮罩',
    onBeforeClose: '关闭前回调，返回 false 可阻止关闭',
    onCancel: '点击取消按钮回调',
    onClosed: '关闭动画结束回调',
    onConfirm: '点击确认按钮回调',
    onOpenChange: '打开状态变化回调',
    onOpened: '打开动画结束回调',
    openAutoFocus: '打开时是否自动聚焦',
    overlayBlur: '遮罩模糊强度',
    placement: '抽屉方向（left/right/top/bottom）',
    showCancelButton: '是否显示取消按钮',
    showConfirmButton: '是否显示确认按钮',
    submitting: '提交锁定状态（禁用关闭等）',
    title: '标题',
    titleTooltip: '标题提示内容',
    zIndex: '层级',
  },
  useVbenForm: {
    actionButtonsReverse: '操作按钮顺序反转（提交前置）',
    actionLayout: '操作按钮布局（inline/newLine/rowEnd）',
    actionPosition: '操作按钮位置（left/center/right）',
    actionWrapperClass: '操作区类名',
    arrayToStringFields: '数组字段与字符串互转配置',
    collapsed: '是否折叠',
    collapsedRows: '折叠时保留行数',
    collapseTriggerResize: '折叠时是否触发尺寸重算（resize）',
    commonConfig: '表单项通用后备配置',
    compact: '紧凑模式（移除校验信息预留空间）',
    fieldMappingTime: '范围时间字段映射到起止字段',
    handleCollapsedChange: '折叠状态变化回调',
    handleReset: '重置回调',
    handleSubmit: '提交回调',
    handleValuesChange: '值变化回调',
    layout: '布局（horizontal/vertical/inline）',
    resetButtonOptions: '重置按钮配置',
    schema: '表单 Schema 配置数组',
    scrollToFirstError: '校验失败时滚动到第一个错误字段',
    showCollapseButton: '是否显示展开/收起按钮',
    showDefaultActions: '是否显示默认操作按钮',
    submitButtonOptions: '提交按钮配置',
    submitOnChange: '值变化时自动提交',
    submitOnEnter: '按回车时自动提交',
    wrapperClass: '表单栅格布局类名',
  },
  useVbenModal: {
    animationType: '动画类型（slide/scale）',
    appendToMain: '是否挂载到主内容区域',
    bordered: '是否显示边框',
    cancelText: '取消按钮文本',
    centered: '是否居中显示',
    class: '弹窗根节点类名',
    closable: '是否显示关闭按钮',
    closeOnClickModal: '点击遮罩时是否关闭',
    closeOnPressEscape: '按 ESC 时是否关闭',
    confirmDisabled: '是否禁用确认按钮',
    confirmLoading: '确认按钮加载状态',
    confirmText: '确认按钮文本',
    contentClass: '内容区域类名',
    description: '弹窗描述文案',
    destroyOnClose: '关闭后是否销毁内容',
    draggable: '是否可拖拽',
    footer: '是否显示底部操作区',
    footerClass: '底部区域类名',
    fullscreen: '是否全屏',
    fullscreenButton: '是否显示全屏按钮',
    header: '是否显示头部',
    headerClass: '头部区域类名',
    isOpen: '是否处于打开状态',
    loading: '是否显示整体加载状态',
    modal: '是否显示遮罩',
    onBeforeClose: '关闭前回调，返回 false 可阻止关闭',
    onCancel: '点击取消按钮回调',
    onClosed: '关闭动画结束回调',
    onConfirm: '点击确认按钮回调',
    onOpenChange: '打开状态变化回调',
    onOpened: '打开动画结束回调',
    openAutoFocus: '打开时是否自动聚焦',
    overlayBlur: '遮罩模糊强度',
    showCancelButton: '是否显示取消按钮',
    showConfirmButton: '是否显示确认按钮',
    submitting: '提交锁定状态（禁用关闭等）',
    title: '标题',
    titleTooltip: '标题提示内容',
    zIndex: '层级',
  },
  useVbenVxeGrid: {
    class: '外层容器类名',
    formOptions: '搜索表单配置（VbenFormProps）',
    gridClass: 'vxe-grid 容器类名',
    gridEvents: 'vxe-grid 事件配置',
    gridOptions: 'vxe-grid 选项配置',
    separator: '搜索表单与表格的分隔条配置',
    showSearchForm: '是否显示搜索表单',
    tableTitle: '表格标题',
    tableTitleHelp: '表格标题帮助信息',
  },
  VxeGridProps: {
    border: '边框样式（boolean 或 default/full/inner/outer）',
    checkboxConfig: '复选列配置',
    columnConfig: '列通用配置',
    columns: '表格列配置',
    customConfig: '自定义列配置',
    data: '表格数据源',
    editConfig: '编辑配置',
    exportConfig: '导出配置',
    filterConfig: '筛选配置',
    height: '表格高度',
    importConfig: '导入配置',
    loading: '加载状态',
    maxHeight: '最大高度',
    pagerConfig: '分页配置',
    printConfig: '打印配置',
    proxyConfig: '代理配置（内置请求流程）',
    radioConfig: '单选列配置',
    rowConfig: '行通用配置',
    seqConfig: '序号列配置',
    showOverflow: '超出隐藏策略（ellipsis/title/tooltip）',
    sortConfig: '排序配置',
    stripe: '斑马纹',
    toolbarConfig: '工具栏配置',
    treeConfig: '树形表格配置',
  },
  VxeGridEvents: {
    cellClick: '单元格点击事件',
    cellDblclick: '单元格双击事件',
    cellMouseenter: '单元格鼠标移入事件',
    cellMouseleave: '单元格鼠标移出事件',
    checkboxAll: '全选复选框变化事件',
    checkboxChange: '行复选框变化事件',
    currentChange: '当前行变化事件',
    editActived: '单元格进入编辑状态事件',
    editClosed: '单元格编辑关闭事件',
    filterChange: '筛选条件变化事件',
    formReset: '内置表单重置事件',
    formSubmit: '内置表单提交事件',
    formSubmitInvalid: '内置表单校验失败事件',
    headerCellClick: '表头单元格点击事件',
    headerCellDblclick: '表头单元格双击事件',
    menuClick: '右键菜单点击事件',
    pageChange: '分页变化事件',
    proxyDelete: 'proxy 删除请求前事件',
    proxyDeleteError: 'proxy 删除失败事件',
    proxyDeleteSuccess: 'proxy 删除成功事件',
    proxyQuery: 'proxy 查询请求前事件',
    proxyQueryError: 'proxy 查询失败事件',
    proxyQuerySuccess: 'proxy 查询成功事件',
    proxySave: 'proxy 保存请求前事件',
    proxySaveError: 'proxy 保存失败事件',
    proxySaveSuccess: 'proxy 保存成功事件',
    radioChange: '单选变化事件',
    scroll: '表格滚动事件',
    sortChange: '排序变化事件',
    toolbarButtonClick: '工具栏按钮点击事件',
    toolbarToolClick: '工具栏工具点击事件',
    validError: '编辑校验失败事件',
  },
  alert: {
    beforeClose: '关闭前回调，返回 false 可阻止关闭',
    bordered: '是否显示边框',
    buttonAlign: '按钮对齐方式（start/center/end）',
    cancelText: '取消按钮文本',
    centered: '是否居中显示',
    confirmText: '确认按钮文本',
    containerClass: '弹窗容器类名',
    content: '弹窗内容（字符串或组件）',
    contentClass: '内容区域类名',
    contentMasking: 'beforeClose 执行时内容区是否显示遮罩',
    footer: '底部附加内容（与按钮同容器）',
    icon: '标题前图标（error/info/question/success/warning）',
    overlayBlur: '遮罩模糊强度',
    showCancel: '是否显示取消按钮',
    title: '弹窗标题',
  },
  confirm: {
    beforeClose: '关闭前回调，返回 false 可阻止关闭',
    bordered: '是否显示边框',
    buttonAlign: '按钮对齐方式（start/center/end）',
    cancelText: '取消按钮文本',
    centered: '是否居中显示',
    confirmText: '确认按钮文本',
    containerClass: '弹窗容器类名',
    content: '弹窗内容（字符串或组件）',
    contentClass: '内容区域类名',
    contentMasking: 'beforeClose 执行时内容区是否显示遮罩',
    footer: '底部附加内容（与按钮同容器）',
    icon: '标题前图标（error/info/question/success/warning）',
    overlayBlur: '遮罩模糊强度',
    showCancel: '是否显示取消按钮',
    title: '弹窗标题',
  },
  prompt: {
    beforeClose: '关闭前回调，返回 false 可阻止关闭（可读取 value）',
    bordered: '是否显示边框',
    buttonAlign: '按钮对齐方式（start/center/end）',
    cancelText: '取消按钮文本',
    centered: '是否居中显示',
    component: '输入组件',
    componentProps: '输入组件属性',
    componentSlots: '输入组件插槽',
    confirmText: '确认按钮文本',
    containerClass: '弹窗容器类名',
    content: '弹窗内容（字符串或组件）',
    contentClass: '内容区域类名',
    contentMasking: 'beforeClose 执行时内容区是否显示遮罩',
    defaultValue: '默认值',
    footer: '底部附加内容（与按钮同容器）',
    icon: '标题前图标（error/info/question/success/warning）',
    modelPropName: '输入组件的值属性名',
    overlayBlur: '遮罩模糊强度',
    showCancel: '是否显示取消按钮',
    title: '弹窗标题',
  },
};

const COMPONENT_OPTIONS = Object.fromEntries(
  Object.entries(COMPONENT_OPTION_META).map(([componentName, meta]) => [
    componentName,
    Object.keys(meta),
  ]),
);

const COMPONENT_OPTION_VALUE_SNIPPETS = {
  useVbenDrawer: {
    appendToMain: '${1:false}',
    cancelText: "'${1:取消}'",
    class: "'${1:}'",
    closable: '${1:true}',
    closeIconPlacement: "'${1:right}'",
    closeOnClickModal: '${1:true}',
    closeOnPressEscape: '${1:true}',
    confirmLoading: '${1:false}',
    confirmText: "'${1:确认}'",
    contentClass: "'${1:}'",
    description: "'${1:}'",
    destroyOnClose: '${1:false}',
    footer: '${1:true}',
    footerClass: "'${1:}'",
    header: '${1:true}',
    headerClass: "'${1:}'",
    isOpen: '${1:false}',
    loading: '${1:false}',
    modal: '${1:true}',
    onBeforeClose: 'async () => {\n    return true;\n  }',
    onCancel: '() => {\n    $1\n  }',
    onClosed: '() => {\n    $1\n  }',
    onConfirm: '() => {\n    $1\n  }',
    onOpenChange: '(isOpen) => {\n    $1\n  }',
    onOpened: '() => {\n    $1\n  }',
    openAutoFocus: '${1:false}',
    overlayBlur: '${1:0}',
    placement: "'${1:right}'",
    showCancelButton: '${1:true}',
    showConfirmButton: '${1:true}',
    submitting: '${1:false}',
    title: "'${1:基础示例}'",
    titleTooltip: "'${1:}'",
    zIndex: '${1:1000}',
  },
  useVbenForm: {
    actionButtonsReverse: '${1:false}',
    actionLayout: "'${1:rowEnd}'",
    actionPosition: "'${1:right}'",
    actionWrapperClass: "'${1:}'",
    arrayToStringFields: '${1:[]}',
    collapsed: '${1:false}',
    collapsedRows: '${1:1}',
    collapseTriggerResize: '${1:false}',
    commonConfig: '{\n    $1\n  }',
    compact: '${1:false}',
    fieldMappingTime: '${1:[]}',
    handleCollapsedChange: '(collapsed) => {\n    $1\n  }',
    handleReset: 'async (values) => {\n    $1\n  }',
    handleSubmit: 'async (values) => {\n    $1\n  }',
    handleValuesChange: '(values, fieldsChanged) => {\n    $1\n  }',
    layout: "'${1:horizontal}'",
    resetButtonOptions: '{\n    $1\n  }',
    schema: '[\n    $1\n  ]',
    scrollToFirstError: '${1:true}',
    showCollapseButton: '${1:true}',
    showDefaultActions: '${1:true}',
    submitButtonOptions: '{\n    $1\n  }',
    submitOnChange: '${1:false}',
    submitOnEnter: '${1:false}',
    wrapperClass: "'${1:grid-cols-1}'",
  },
  useVbenModal: {
    animationType: "'${1:slide}'",
    appendToMain: '${1:false}',
    bordered: '${1:true}',
    cancelText: "'${1:取消}'",
    centered: '${1:false}',
    class: "'${1:}'",
    closable: '${1:true}',
    closeOnClickModal: '${1:true}',
    closeOnPressEscape: '${1:true}',
    confirmDisabled: '${1:false}',
    confirmLoading: '${1:false}',
    confirmText: "'${1:确认}'",
    contentClass: "'${1:}'",
    description: "'${1:}'",
    destroyOnClose: '${1:true}',
    draggable: '${1:false}',
    footer: '${1:true}',
    footerClass: "'${1:}'",
    fullscreen: '${1:false}',
    fullscreenButton: '${1:true}',
    header: '${1:true}',
    headerClass: "'${1:}'",
    isOpen: '${1:false}',
    loading: '${1:false}',
    modal: '${1:true}',
    onBeforeClose: 'async () => {\n    return true;\n  }',
    onCancel: '() => {\n    $1\n  }',
    onClosed: '() => {\n    $1\n  }',
    onConfirm: '() => {\n    $1\n  }',
    onOpenChange: '(isOpen) => {\n    $1\n  }',
    onOpened: '() => {\n    $1\n  }',
    openAutoFocus: '${1:false}',
    overlayBlur: '${1:0}',
    showCancelButton: '${1:true}',
    showConfirmButton: '${1:true}',
    submitting: '${1:false}',
    title: "'${1:基础示例}'",
    titleTooltip: "'${1:}'",
    zIndex: '${1:1000}',
  },
  useVbenVxeGrid: {
    class: "'${1:}'",
    formOptions: '{\n    $1\n  }',
    gridClass: "'${1:}'",
    gridEvents: '{\n    $1\n  }',
    gridOptions: '{\n    $1\n  }',
    separator: '${1:true}',
    showSearchForm: '${1:true}',
    tableTitle: "'${1:列表}'",
    tableTitleHelp: "'${1:}'",
  },
  VxeGridProps: {
    border: "'${1:full}'",
    checkboxConfig: '{\n    $1\n  }',
    columnConfig: '{\n    $1\n  }',
    columns: '[\n    $1\n  ]',
    customConfig: '{\n    $1\n  }',
    data: '${1:[]}',
    editConfig: '{\n    $1\n  }',
    exportConfig: '{\n    $1\n  }',
    filterConfig: '{\n    $1\n  }',
    height: "'${1:auto}'",
    importConfig: '{\n    $1\n  }',
    loading: '${1:false}',
    maxHeight: '${1:600}',
    pagerConfig: '{\n    enabled: ${1:false},\n  }',
    printConfig: '{\n    $1\n  }',
    proxyConfig: '{\n    $1\n  }',
    radioConfig: '{\n    $1\n  }',
    rowConfig: '{\n    $1\n  }',
    seqConfig: '{\n    $1\n  }',
    showOverflow: "'${1:tooltip}'",
    sortConfig: '{\n    $1\n  }',
    stripe: '${1:true}',
    toolbarConfig: '{\n    $1\n  }',
    treeConfig: '{\n    $1\n  }',
  },
  alert: {
    beforeClose: 'async ({ isConfirm }) => {\n    return true;\n  }',
    bordered: '${1:false}',
    buttonAlign: "'${1:end}'",
    cancelText: "'${1:取消}'",
    centered: '${1:false}',
    confirmText: "'${1:确认}'",
    containerClass: "'${1:}'",
    content: "'${1:提示内容}'",
    contentClass: "'${1:}'",
    contentMasking: '${1:false}',
    footer: "'${1:}'",
    icon: "'${1:info}'",
    overlayBlur: '${1:0}',
    showCancel: '${1:false}',
    title: "'${1:提示}'",
  },
  confirm: {
    beforeClose: 'async ({ isConfirm }) => {\n    return true;\n  }',
    bordered: '${1:false}',
    buttonAlign: "'${1:end}'",
    cancelText: "'${1:取消}'",
    centered: '${1:false}',
    confirmText: "'${1:确认}'",
    containerClass: "'${1:}'",
    content: "'${1:确认继续吗？}'",
    contentClass: "'${1:}'",
    contentMasking: '${1:false}',
    footer: "'${1:}'",
    icon: "'${1:question}'",
    overlayBlur: '${1:0}',
    showCancel: '${1:true}',
    title: "'${1:确认}'",
  },
  prompt: {
    beforeClose:
      'async ({ isConfirm, value }) => {\n    if (isConfirm && !value) {\n      return false;\n    }\n    return true;\n  }',
    bordered: '${1:false}',
    buttonAlign: "'${1:end}'",
    cancelText: "'${1:取消}'",
    centered: '${1:false}',
    component: '${1:Input}',
    componentProps: '{\n    $1\n  }',
    componentSlots: '{\n    $1\n  }',
    confirmText: "'${1:确认}'",
    containerClass: "'${1:}'",
    content: "'${1:请输入内容}'",
    contentClass: "'${1:}'",
    contentMasking: '${1:true}',
    defaultValue: "'${1:}'",
    footer: "'${1:}'",
    icon: "'${1:question}'",
    modelPropName: "'${1:modelValue}'",
    overlayBlur: '${1:0}',
    showCancel: '${1:true}',
    title: "'${1:输入}'",
  },
};

const COMPONENT_OPTION_VALUE_ENUMS = {
  alert: {
    buttonAlign: ['start', 'center', 'end'],
    icon: ['error', 'info', 'question', 'success', 'warning'],
  },
  confirm: {
    buttonAlign: ['start', 'center', 'end'],
    icon: ['error', 'info', 'question', 'success', 'warning'],
  },
  prompt: {
    buttonAlign: ['start', 'center', 'end'],
    icon: ['error', 'info', 'question', 'success', 'warning'],
  },
  useVbenDrawer: {
    closeIconPlacement: ['left', 'right'],
    placement: ['bottom', 'left', 'right', 'top'],
  },
  useVbenForm: {
    actionLayout: ['inline', 'newLine', 'rowEnd'],
    actionPosition: ['center', 'left', 'right'],
    layout: ['horizontal', 'inline', 'vertical'],
  },
  useVbenModal: {
    animationType: ['scale', 'slide'],
  },
  VxeGridProps: {
    border: ['default', 'full', 'inner', 'outer'],
    showOverflow: ['ellipsis', 'title', 'tooltip'],
  },
};

const API_METHODS = {
  drawerApi: [
    'close',
    'getData',
    'lock',
    'onCancel',
    'onClosed',
    'onConfirm',
    'onOpened',
    'open',
    'setData',
    'setState',
    'unlock',
    'useStore',
  ],
  formApi: [
    'getFieldComponentRef',
    'getFocusedField',
    'getLatestSubmissionValues',
    'getState',
    'getValues',
    'isFieldValid',
    'merge',
    'mount',
    'removeSchemaByFields',
    'resetForm',
    'resetValidate',
    'scrollToFirstError',
    'setFieldValue',
    'setState',
    'setValues',
    'submitForm',
    'unmount',
    'updateSchema',
    'useStore',
    'validate',
    'validateAndSubmitForm',
    'validateField',
  ],
  gridApi: [
    'mount',
    'query',
    'reload',
    'setGridOptions',
    'setLoading',
    'setState',
    'toggleSearchForm',
    'unmount',
    'useStore',
  ],
  modalApi: [
    'close',
    'getData',
    'lock',
    'onCancel',
    'onClosed',
    'onConfirm',
    'onOpened',
    'open',
    'setData',
    'setState',
    'unlock',
    'useStore',
  ],
};
export {
  API_DOCS_URL_MAP,
  API_METHODS,
  COMPONENT_OPTION_META,
  COMPONENT_OPTIONS,
  COMPONENT_OPTION_VALUE_ENUMS,
  COMPONENT_OPTION_VALUE_SNIPPETS,
  DOCS_URL,
  FUNCTION_DOCS_URL_MAP,
  SNIPPET_DOCS_URL_MAP,
  VBEN_PAGE_TEMPLATE_SNIPPETS,
  VBEN_SCRIPT_SNIPPETS,
};
